// Generated by CoffeeScript 1.10.0
(function() {
  var base;

  if (typeof vehicle.startEngine === "function") {
    if (typeof (base = vehicle.startEngine()).shiftGear === "function") {
      base.shiftGear();
    }
  }

}).call(this);
