version: '3.8'
services:
  mongodb:
    image: "mongodb"
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USER=max
      - MONGO_INITDB_ROOT_ROOT=secret
      # MONGO_INITDB_ROOT_ROOT: secret
    env_file:
      - ./env/mongo.env
    # Not needed, will be create a network for all services in this compose file already.
    networks:
      - my_network
  backend:
  frontend:

  volumes:
    # Do not need specify anonymous volumes and bind volumes.
    data:
